### ISSUE TITLE
Ensure iFrame is correct height on desktop, mobile and tablet

### ISSUE THREAD

**Issue by dtoakley** [global-climate-strikes/digital-climate-strike#20]

**Comment by jlevers** [comment]
Assuming that the correct height just means that it looks reasonable, and not something more specific, it looks good to me. I've attached some screenshots taken from manipulating my browser window size and user agent with Chrome devtools.

Desktop
![image](https://user-images.githubusercontent.com/4974856/63232591-3e6e2700-c1f7-11e9-964d-a82e5b9b1c5b.png)

Tablet (looks like the right height but the close widget "X" button needs to be moved)
![image](https://user-images.githubusercontent.com/4974856/63245244-a8092800-c22d-11e9-96c4-84c84c2fe0c0.png)

Mobile (same issue as tablet view)
![image](https://user-images.githubusercontent.com/4974856/63245312-dd157a80-c22d-11e9-844c-14f40a21168e.png)

**Comment by dtoakley** [comment]
Yep, I tested this yesterday as well and it looked good to me. Closing this issue.
